### PR TITLE
Improved formatting of type annotations.

### PR DESCRIPTION
**Pull request by wheerd**
Imrpoved the formatting of generic type annotations. See agronholm/sphinx-autodoc-typehints#7 for details.

### CODE REVIEW

**Comment by wheerd** [comment]
I didn't notice you had tests so I guess those are not working :(

**Comment by daviskirk** [comment]
Hey thanks for this, read through the thread and all of the changes seems like smart choices.
Yeah, the tests are basically just to make sure the html output is as expected.  You can just change the "expected" lines that this changes in the test (just 3 lines are different as far as I can see [hear]https://travis-ci.org/daviskirk/sphinx-autodoc-napoleon-typehints/builds/170705459)).

Also, I like the tests you're trying to get merged into https://github.com/agronholm/sphinx-autodoc-typehints/pull/7#pullrequestreview-2960572 .  Once they're in there I'll probably bring them over here too if that's ok with you!  Thanks for the changes!

**Comment by wheerd** [comment]
Sure, I can include the tests in the pull request too if you wish. 

BTW, I am pretty sure hat testing the HTML output is not the way to go. That will break super easily if something (minor) in Sphinx changes (as you can see with the current build). You could just turn the examples from your documentation into tests.

**Comment by daviskirk** [comment]
I'm definitly with you on the html issue.  Starting out, I just wanted some sort of end to end test that would cut through the whole stack and explode if something went wrong.  The html output was the only way I could think of to actually test that the code works with sphinx.  Just testing the formatter leaves alot of room for breaking in the plugin/processing part of the code.

However, together with your formatting tests, I might reduce the html test code to just check if it outputs anything at all.  That might be more manageable. Unless you meant something else entirely, in which case I'm open to suggestions.

**Comment by wheerd** [comment]
I was thinking of something like this:

```python
import inspect
import os
import sys

try:
    from backports.typing import Union
except ImportError:
    from typing import Union

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from sphinx_autodoc_napoleon_typehints import process_docstring

def format_unit(value: Union[float, int], unit: str) -> str:
    """
    Formats the given value as a human readable string using the given units.

    :param value: a numeric value
    :param unit: the unit for the value (kg, m, etc.)
    """
    return '{} {}'.format(value, unit)

expected = """
    Formats the given value as a human readable string using the given units.

    :type value: :class:`~typing.Union`\\[:class:`float`, :class:`int`]
    :param value: a numeric value
    :type unit: :class:`str`
    :param unit: the unit for the value (kg, m, etc.)
    :rtype: :class:`str`
    """

def test_process_docstring():
    lines = inspect.cleandoc(format_unit.__doc__).splitlines()
    expected_lines = inspect.cleandoc(expected).splitlines()

    process_docstring(None, 'function', format_unit.__name__, format_unit, {}, lines)

    assert lines == expected_lines
```

A couple more tests like that should cover the functionality pretty well nad only test your code. You can also use pytest's [parametrize](http://doc.pytest.org/en/latest/parametrize.html) to easily create more tests like that.

**Comment by daviskirk** [comment]
Good idea to use the inspect module for this.  Thanks again!

**Pull request merged**
